name: flutter_chat
description: "Flutter chat app with Cerebras AI backend."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  
  # Storage & Persistence
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  
  # Permissions & Platform
  permission_handler: ^12.0.1
  connectivity_plus: ^6.0.5
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.2
  
  # Payment Features
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
